#ifndef AXIOLID_CAPI_V0_4_H
#define AXIOLID_CAPI_V0_4_H

#pragma once

/* Generated by `cargo xtask ffi header`; do not edit manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * v0.4 ABI status code.
 */
enum AxiolidStatus
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  AxiolidStatus_Ok = 0,
  AxiolidStatus_NullPointer = 1,
  AxiolidStatus_InvalidArgument = 2,
  AxiolidStatus_InvalidHandle = 3,
  AxiolidStatus_LimitExceeded = 4,
  AxiolidStatus_Unsupported = 5,
  AxiolidStatus_UnsupportedExact = 6,
  AxiolidStatus_BufferTooSmall = 7,
  AxiolidStatus_OperationFailed = 8,
  AxiolidStatus_WrongResultKind = 9,
  AxiolidStatus_NoError = 10,
  AxiolidStatus_Panic = 255,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AxiolidStatus AxiolidStatus;
#else
typedef int32_t AxiolidStatus;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Operation identifier in a capability descriptor.
 */
enum AxiolidOperation
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  AxiolidOperation_CurveEvaluation = 1,
  AxiolidOperation_SurfaceEvaluation = 2,
  AxiolidOperation_ProfileTriangulation = 3,
  AxiolidOperation_Sweep = 4,
  AxiolidOperation_Tessellation = 5,
  AxiolidOperation_MeshBoolean = 6,
  AxiolidOperation_MeshPlaneSection = 7,
  AxiolidOperation_SpatialQuery = 8,
  AxiolidOperation_Measurement = 9,
  AxiolidOperation_Healing = 10,
  AxiolidOperation_GraphCompilation = 11,
  AxiolidOperation_Unknown = 255,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AxiolidOperation AxiolidOperation;
#else
typedef int32_t AxiolidOperation;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Representation identifier in a capability descriptor.
 */
enum AxiolidRepresentation
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  AxiolidRepresentation_Scalar = 1,
  AxiolidRepresentation_Linear = 2,
  AxiolidRepresentation_Profile2d = 3,
  AxiolidRepresentation_AnalyticCurve = 4,
  AxiolidRepresentation_AnalyticSurface = 5,
  AxiolidRepresentation_Topology = 6,
  AxiolidRepresentation_ExactBrep = 7,
  AxiolidRepresentation_TriangleMesh = 8,
  AxiolidRepresentation_MeshHealth = 9,
  AxiolidRepresentation_Measurements = 10,
  AxiolidRepresentation_RayHit = 11,
  AxiolidRepresentation_ModelGraph = 12,
  AxiolidRepresentation_SampledField = 13,
  AxiolidRepresentation_Unknown = 255,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AxiolidRepresentation AxiolidRepresentation;
#else
typedef int32_t AxiolidRepresentation;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Exactness promise in a capability descriptor.
 */
enum AxiolidExactness
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  AxiolidExactness_Exact = 1,
  AxiolidExactness_ToleranceBounded = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AxiolidExactness AxiolidExactness;
#else
typedef int32_t AxiolidExactness;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Representation stored by an operation result.
 */
enum AxiolidGeometryKind
#if __STDC_VERSION__ >= 202311L
  : int32_t
#endif // __STDC_VERSION__ >= 202311L
 {
  AxiolidGeometryKind_TriangleMesh = 1,
  AxiolidGeometryKind_ExactBrep = 2,
  AxiolidGeometryKind_Unknown = 255,
};
#if __STDC_VERSION__ >= 202311L
typedef enum AxiolidGeometryKind AxiolidGeometryKind;
#else
typedef int32_t AxiolidGeometryKind;
#endif // __STDC_VERSION__ >= 202311L

/**
 * Globally unique opaque context token. Zero is always invalid.
 */
typedef uint64_t AxiolidContextHandle;
#define AxiolidContextHandle_INVALID 0

/**
 * Globally unique opaque mesh token owned by an Axiolid context.
 */
typedef uint64_t AxiolidMeshHandle;
#define AxiolidMeshHandle_INVALID 0

/**
 * Stable Boolean operand. An integer alias keeps unknown C values defined.
 */
typedef int32_t AxiolidBooleanOperator;

/**
 * Caller-supplied tolerance in model units and radians.
 */
typedef struct {
  double linear;
  double angular;
} AxiolidTolerance;

/**
 * Globally unique opaque operation-result token owned by a context.
 */
typedef uint64_t AxiolidResultHandle;
#define AxiolidResultHandle_INVALID 0

/**
 * Stable, pointer-free capability description. String lengths exclude padding.
 */
typedef struct {
  AxiolidOperation operation;
  AxiolidRepresentation representation;
  AxiolidExactness exactness;
  uint8_t id[64];
  uint8_t provider[64];
  uint8_t required_feature[32];
  uint8_t id_len;
  uint8_t provider_len;
  uint8_t required_feature_len;
  uint8_t deterministic;
} AxiolidCapabilityDescriptor;

/**
 * Stable provider bundle selection. Integer form makes unknown C values rejectable.
 */
typedef int32_t AxiolidProviderProfile;

/**
 * Hard allocation budgets and provider selection for one context.
 */
typedef struct {
  AxiolidProviderProfile provider_profile;
  uint32_t max_meshes;
  uint32_t max_results;
  uint32_t max_vertices_per_mesh;
  uint32_t max_triangles_per_mesh;
} AxiolidContextConfig;

/**
 * Structured portion of a context-owned error record.
 */
typedef struct {
  AxiolidStatus status;
  AxiolidOperation operation;
  AxiolidTolerance tolerance;
  uint8_t provider[64];
  size_t message_len;
  uint8_t provider_len;
  /**
   * Must be zero; reserves layout space without exposing padding bytes.
   */
  uint8_t reserved[7];
} AxiolidErrorInfo;

/**
 * Stable mesh-audit summary.
 */
typedef struct {
  size_t vertex_count;
  size_t triangle_count;
  uint8_t closed_two_manifold;
  /**
   * Must be zero; reserves layout space without exposing padding bytes.
   */
  uint8_t reserved[7];
} AxiolidMeshAudit;

/**
 * Axis-aligned mesh bounds.
 */
typedef struct {
  double min[3];
  double max[3];
} AxiolidBounds;

/**
 * Surface and signed-volume measurements.
 */
typedef struct {
  double surface_area;
  double signed_volume;
  double surface_centroid[3];
  double volume_centroid[3];
} AxiolidMeasurements;

/**
 * Column-major affine transform.
 */
typedef struct {
  double columns[16];
} AxiolidTransform;

/**
 * Semantic ABI and package version.
 */
typedef struct {
  uint16_t abi_major;
  uint16_t abi_minor;
  uint16_t abi_patch;
  uint16_t crate_major;
  uint16_t crate_minor;
  uint16_t crate_patch;
} AxiolidVersion;

#define AXIOLID_BOOLEAN_DIFFERENCE 3

#define AXIOLID_BOOLEAN_INTERSECTION 2

#define AXIOLID_BOOLEAN_SYMMETRIC_DIFFERENCE 4

#define AXIOLID_BOOLEAN_UNION 1

#define AXIOLID_PROVIDER_PORTABLE 1

/**
 * Execute a tolerance-bounded mesh Boolean and return an owned result handle.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_boolean(AxiolidContextHandle context,
                                   AxiolidMeshHandle subject,
                                   AxiolidMeshHandle tool,
                                   AxiolidBooleanOperator operator_,
                                   AxiolidTolerance tolerance_value,
                                   AxiolidResultHandle *out_result);

/**
 * Query the number of capabilities callable through this ABI context.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_capability_count(AxiolidContextHandle context, size_t *out_count);

/**
 * Copy one capability descriptor into caller-owned storage.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_capability_get(AxiolidContextHandle context,
                                          size_t index,
                                          AxiolidCapabilityDescriptor *out_descriptor);

/**
 * Create and transfer ownership of a context handle to the caller.
 *
 * Both pointers must refer to readable/writable instances for the duration of this call.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_context_create(const AxiolidContextConfig *config,
                                          AxiolidContextHandle *out_context);

/**
 * Destroy a context and all child objects it owns.
 *
 * A stale or repeatedly destroyed handle is rejected without dereferencing freed memory.
 */
AxiolidStatus axiolid_v0_4_context_destroy(AxiolidContextHandle context);

/**
 * Copy structured metadata for the context's most recent error.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_context_last_error_info(AxiolidContextHandle context,
                                                   AxiolidErrorInfo *out_info);

/**
 * Copy the last error message into a caller-owned UTF-8 buffer.
 *
 * `out_required` receives the byte count including the trailing NUL. Passing a
 * null buffer with zero capacity is the supported sizing query.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_context_last_error_message(AxiolidContextHandle context,
                                                      uint8_t *buffer,
                                                      size_t capacity,
                                                      size_t *out_required);

/**
 * Query live child-object counts for leak checks and shutdown assertions.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_context_live_object_counts(AxiolidContextHandle context,
                                                      size_t *out_meshes,
                                                      size_t *out_results);

/**
 * Exact Boolean is not part of v0.4; this function fails closed by contract.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_exact_boolean(AxiolidContextHandle context,
                                         AxiolidMeshHandle subject,
                                         AxiolidMeshHandle tool,
                                         AxiolidTolerance tolerance_value,
                                         AxiolidResultHandle *out_result);

/**
 * Construct an exact rectangular prism; no mesh fallback is permitted.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_exact_extrude_rectangle(AxiolidContextHandle context,
                                                   double width,
                                                   double height,
                                                   double depth,
                                                   AxiolidTolerance tolerance_value,
                                                   AxiolidResultHandle *out_result);

/**
 * Audit mesh topology under an explicit tolerance.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_mesh_audit(AxiolidContextHandle context,
                                      AxiolidMeshHandle mesh,
                                      AxiolidTolerance tolerance_value,
                                      AxiolidMeshAudit *out_audit);

/**
 * Compute axis-aligned bounds for a non-empty mesh.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_mesh_bounds(AxiolidContextHandle context,
                                       AxiolidMeshHandle mesh,
                                       AxiolidBounds *out_bounds);

/**
 * Copy an indexed mesh into exactly-sized, caller-owned output buffers.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented write extent. The
 * position and index output ranges must not overlap.
 */
AxiolidStatus axiolid_v0_4_mesh_copy(AxiolidContextHandle context,
                                     AxiolidMeshHandle mesh,
                                     double *out_positions_xyz,
                                     size_t vertex_capacity,
                                     uint32_t *out_triangle_indices,
                                     size_t triangle_capacity);

/**
 * Query vertex and triangle counts before allocating export buffers.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_mesh_counts(AxiolidContextHandle context,
                                       AxiolidMeshHandle mesh,
                                       size_t *out_vertex_count,
                                       size_t *out_triangle_count);

/**
 * Destroy a mesh handle. Repeated destruction returns `InvalidHandle`.
 */
AxiolidStatus axiolid_v0_4_mesh_destroy(AxiolidContextHandle context, AxiolidMeshHandle mesh);

/**
 * Import an indexed triangle mesh. Input buffers are borrowed for this call only.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_mesh_import(AxiolidContextHandle context,
                                       const double *positions_xyz,
                                       size_t vertex_count,
                                       const uint32_t *triangle_indices,
                                       size_t triangle_count,
                                       AxiolidMeshHandle *out_mesh);

/**
 * Measure surface area and signed volume under an explicit tolerance.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_mesh_measure(AxiolidContextHandle context,
                                        AxiolidMeshHandle mesh,
                                        AxiolidTolerance tolerance_value,
                                        AxiolidMeasurements *out_measurements);

/**
 * Apply a finite affine transform to mesh positions in place.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_mesh_transform(AxiolidContextHandle context,
                                          AxiolidMeshHandle mesh,
                                          const AxiolidTransform *transform);

/**
 * Destroy an operation result and its owned geometry.
 */
AxiolidStatus axiolid_v0_4_result_destroy(AxiolidContextHandle context, AxiolidResultHandle result);

/**
 * Query whether a result owns an exact B-rep or triangle mesh.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_result_kind(AxiolidContextHandle context,
                                       AxiolidResultHandle result,
                                       AxiolidGeometryKind *out_kind);

/**
 * Consume a mesh result and transfer its mesh to a new context-owned mesh handle.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_result_take_mesh(AxiolidContextHandle context,
                                            AxiolidResultHandle result,
                                            AxiolidMeshHandle *out_mesh);

/**
 * Subtract a borrowed array of mesh handles from one subject mesh.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_subtract_many(AxiolidContextHandle context,
                                         AxiolidMeshHandle subject,
                                         const AxiolidMeshHandle *tools,
                                         size_t tool_count,
                                         AxiolidTolerance tolerance_value,
                                         AxiolidResultHandle *out_result);

/**
 * Write the ABI/package version to caller-owned memory.
 *
 * `out_version` must be null or point to writable storage for one `AxiolidVersion`.
 * # Safety
 * Every non-null pointer must be aligned and valid for the documented read or write extent.
 */
AxiolidStatus axiolid_v0_4_version(AxiolidVersion *out_version);

#endif  /* AXIOLID_CAPI_V0_4_H */
