get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../.." ABSOLUTE)
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
  message(FATAL_ERROR "Axiolid ABI v0.4 supports only 64-bit consumers")
endif()
if(WIN32 AND NOT MSVC)
  message(FATAL_ERROR "Axiolid ABI v0.4 Windows packages require MSVC")
endif()
if(NOT DEFINED AXIOLID_LINKAGE)
  set(AXIOLID_LINKAGE "SHARED")
endif()
string(TOUPPER "${AXIOLID_LINKAGE}" AXIOLID_LINKAGE)
if(NOT AXIOLID_LINKAGE MATCHES "^(SHARED|STATIC)$")
  set(Axiolid_FOUND FALSE)
  set(Axiolid_NOT_FOUND_MESSAGE "AXIOLID_LINKAGE must be SHARED or STATIC")
  return()
endif()
include("${CMAKE_CURRENT_LIST_DIR}/AxiolidTargets.cmake")
