set(PACKAGE_VERSION "0.4.0")
if(PACKAGE_FIND_VERSION_MAJOR EQUAL 0 AND PACKAGE_FIND_VERSION_MINOR EQUAL 4 AND
   NOT PACKAGE_FIND_VERSION VERSION_GREATER PACKAGE_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()
if(PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
  set(PACKAGE_VERSION_EXACT TRUE)
endif()
