use axiolid_contracts::{capability_ids, Ownership, ThreadSafety, V04_PROFILE_CONTRACTS};

fn main() {
    println!("# Downstream integration profiles\n");
    println!("Generated by `cargo run -q -p axiolid-contracts --example downstream_profiles`. Do not edit by hand.\n");
    println!("The v0.4 protocol supports three consumption profiles. These rows define boundary compatibility; they do **not** claim that every operation is available. A concrete build must return an `IntegrationDescriptor`, and an operation is advertised only after a provider implementing its operation trait is present and exercised. See [ADR 0039](../adr/0039-downstream-integration-contract.md).\n");
    println!("| Profile | Transport | Discovery | Compatibility | API | ABI | MSRV | Ownership | Thread safety |");
    println!("| --- | --- | --- | --- | --- | --- | --- | --- | --- |");
    for profile in V04_PROFILE_CONTRACTS {
        let api = format!(
            "{}.{}.{}",
            profile.api_version.major, profile.api_version.minor, profile.api_version.patch
        );
        let abi = profile
            .abi_version
            .map(|version| format!("{}.{}.{}", version.major, version.minor, version.patch))
            .unwrap_or_else(|| "—".to_owned());
        let msrv = profile.minimum_rust_version.unwrap_or("—");
        println!(
            "| `{}` | {} | {} | {} | {} | {} | {} | {} | {} |",
            profile.name,
            profile.transport,
            profile.capability_discovery,
            profile.compatibility,
            api,
            abi,
            msrv,
            ownership(profile.boundary.ownership),
            thread_safety(profile.boundary.thread_safety),
        );
    }

    println!("\n## Boundary invariants\n");
    println!("All profiles use right-handed Cartesian `f64` coordinates. Geometry is unitless: coordinates and every explicit tolerance use one caller-selected unit. Approximate or discretizing work requires a caller-visible tolerance. Exact requests either return exact analytic/topological results or typed refusal; they never silently return meshes. Rust values own their allocations. Native outputs are opaque handles released by their matching Axiolid destructor.\n");
    println!("## Versioned capability vocabulary\n");
    println!("The protocol recognizes these stable identifiers. Presence here defines vocabulary, not runtime availability; only the descriptor returned by the current build may claim availability.\n");
    println!("| Capability identifier |");
    println!("| --- |");
    for id in capability_ids::ALL {
        println!("| `{}` |", id.as_str());
    }

    println!("\n## Typed handshake\n");
    println!("Consumers submit a `CapabilityRequirement` containing a versioned capability ID, required output representation, and required fidelity. `IntegrationDescriptor::require` returns the matching descriptor or a typed `RequirementRefusal` (`ApiVersion`, `CapabilityUnavailable`, `RepresentationUnavailable`, or `ExactnessUnavailable`). This check performs no fallback. Provider selection remains explicit and operation traits remain the capability truth.\n");
    println!("## Verification\n");
    println!("Run `scripts/check-integration-contract.sh` to regenerate this document in memory and compare it byte-for-byte. Run `scripts/probe_integration_contract_gate.py` to prove the gate detects a removed promised identifier and restores the source tree.");
}

fn ownership(value: Ownership) -> &'static str {
    match value {
        Ownership::RustValues => "Rust-owned values",
        Ownership::OpaqueOwnedHandles => "opaque owned handles",
    }
}

fn thread_safety(value: ThreadSafety) -> &'static str {
    match value {
        ThreadSafety::SendSyncValues => "`Send + Sync` values",
        ThreadSafety::ContextSendNotSync => "context `Send`, not `Sync`",
    }
}
